//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.19 at 01:31:41 PM CEST 
//


package gov.sec.ratings;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://xbrl.sec.gov/ratings/2015-03-31}OBT"/&gt;
 *         &lt;element ref="{http://xbrl.sec.gov/ratings/2015-03-31}INSTNAME"/&gt;
 *         &lt;choice&gt;
 *           &lt;sequence&gt;
 *             &lt;element ref="{http://xbrl.sec.gov/ratings/2015-03-31}CUSIP"/&gt;
 *             &lt;group ref="{http://xbrl.sec.gov/ratings/2015-03-31}InstrumentIdentifier" minOccurs="0"/&gt;
 *           &lt;/sequence&gt;
 *           &lt;group ref="{http://xbrl.sec.gov/ratings/2015-03-31}InstrumentIdentifier"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element ref="{http://xbrl.sec.gov/ratings/2015-03-31}IRTD" minOccurs="0"/&gt;
 *         &lt;element ref="{http://xbrl.sec.gov/ratings/2015-03-31}CR" minOccurs="0"/&gt;
 *         &lt;element ref="{http://xbrl.sec.gov/ratings/2015-03-31}MD" minOccurs="0"/&gt;
 *         &lt;element ref="{http://xbrl.sec.gov/ratings/2015-03-31}PV" minOccurs="0"/&gt;
 *         &lt;element ref="{http://xbrl.sec.gov/ratings/2015-03-31}ISUD" minOccurs="0"/&gt;
 *         &lt;element ref="{http://xbrl.sec.gov/ratings/2015-03-31}RODC" minOccurs="0"/&gt;
 *         &lt;element ref="{http://xbrl.sec.gov/ratings/2015-03-31}INRD" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attGroup ref="{http://www.xbrl.org/2003/instance}tupleAttrs"/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
public class IND {

  @XmlElementRefs({
      @XmlElementRef(name = "OBT", namespace = "http://xbrl.sec.gov/ratings/2015-03-31", type = JAXBElement.class, required = false),
      @XmlElementRef(name = "INSTNAME", namespace = "http://xbrl.sec.gov/ratings/2015-03-31", type = JAXBElement.class, required = false),
      @XmlElementRef(name = "CUSIP", namespace = "http://xbrl.sec.gov/ratings/2015-03-31", type = JAXBElement.class, required = false),
      @XmlElementRef(name = "INI", namespace = "http://xbrl.sec.gov/ratings/2015-03-31", type = JAXBElement.class, required = false),
      @XmlElementRef(name = "INIS", namespace = "http://xbrl.sec.gov/ratings/2015-03-31", type = JAXBElement.class, required = false),
      @XmlElementRef(name = "INIOS", namespace = "http://xbrl.sec.gov/ratings/2015-03-31", type = JAXBElement.class, required = false),
      @XmlElementRef(name = "IRTD", namespace = "http://xbrl.sec.gov/ratings/2015-03-31", type = JAXBElement.class, required = false),
      @XmlElementRef(name = "CR", namespace = "http://xbrl.sec.gov/ratings/2015-03-31", type = JAXBElement.class, required = false),
      @XmlElementRef(name = "MD", namespace = "http://xbrl.sec.gov/ratings/2015-03-31", type = JAXBElement.class, required = false),
      @XmlElementRef(name = "PV", namespace = "http://xbrl.sec.gov/ratings/2015-03-31", type = JAXBElement.class, required = false),
      @XmlElementRef(name = "ISUD", namespace = "http://xbrl.sec.gov/ratings/2015-03-31", type = JAXBElement.class, required = false),
      @XmlElementRef(name = "RODC", namespace = "http://xbrl.sec.gov/ratings/2015-03-31", type = JAXBElement.class, required = false),
      @XmlElementRef(name = "INRD", namespace = "http://xbrl.sec.gov/ratings/2015-03-31", type = JAXBElement.class, required = false)
  })
  protected List<JAXBElement<?>> content;
  @XmlAttribute(name = "id")
  @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
  @XmlID
  @XmlSchemaType(name = "ID")
  protected String id;
  @XmlAnyAttribute
  private Map<QName, String> otherAttributes = new HashMap<QName, String>();

  /**
   * Gets the rest of the content model.
   *
   * <p>
   * You are getting this "catch-all" property because of the following reason: The field name "INI" is used by two different parts of a schema. See: line 392
   * of file:/C:/Users/e.uezuemlueoglu/dev/workspace/sec-reporting/sec-module-xbrlgenerator/src/main/resources/schema/ratings-2015-03-31.xsd line 392 of
   * file:/C:/Users/e.uezuemlueoglu/dev/workspace/sec-reporting/sec-module-xbrlgenerator/src/main/resources/schema/ratings-2015-03-31.xsd
   * <p>
   * To get rid of this property, apply a property customization to one of both of the following declarations to change their names: Gets the value of the
   * content property.
   *
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside
   * the JAXB object. This is why there is not a <CODE>set</CODE> method for the content property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   * <pre>
   *    getContent().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list {@link JAXBElement }{@code <}{@link OBT }{@code >} {@link JAXBElement }{@code <}{@link
   * StringItemType }{@code >} {@link JAXBElement }{@code <}{@link CusipItemType }{@code >} {@link JAXBElement }{@code <}{@link StringItemType }{@code >} {@link
   * JAXBElement }{@code <}{@link INIS }{@code >} {@link JAXBElement }{@code <}{@link StringItemType }{@code >} {@link JAXBElement }{@code <}{@link
   * StringItemType }{@code >} {@link JAXBElement }{@code <}{@link PureItemType }{@code >} {@link JAXBElement }{@code <}{@link DateItemType }{@code >} {@link
   * JAXBElement }{@code <}{@link MonetaryItemType }{@code >} {@link JAXBElement }{@code <}{@link DateItemType }{@code >} {@link JAXBElement }{@code <}{@link
   * StringItemType }{@code >} {@link JAXBElement }{@code <}{@link RatingDetailType }{@code >}
   */
  public List<JAXBElement<?>> getContent() {
    if (content == null) {
      content = new ArrayList<JAXBElement<?>>();
    }
    return this.content;
  }

  /**
   * Gets the value of the id property.
   *
   * @return possible object is {@link String }
   */
  public String getId() {
    return id;
  }

  /**
   * Sets the value of the id property.
   *
   * @param value allowed object is {@link String }
   */
  public void setId(String value) {
    this.id = value;
  }

  /**
   * Gets a map that contains attributes that aren't bound to any typed property on this class.
   *
   * <p>
   * the map is keyed by the name of the attribute and the value is the string value of the attribute.
   * <p>
   * the map returned by this method is live, and you can add new attribute by updating the map directly. Because of this design, there's no setter.
   *
   * @return always non-null
   */
  public Map<QName, String> getOtherAttributes() {
    return otherAttributes;
  }

}
