//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.19 at 01:31:41 PM CEST 
//


package gov.sec.ratings;

import javax.xml.bind.JAXBElement;
import javax.xml.namespace.QName;

public class LinkbaseDocumentationType
    extends JAXBElement<DocumentationType> {

  protected final static QName NAME = new QName("http://www.xbrl.org/2003/linkbase", "documentation");

  public LinkbaseDocumentationType(DocumentationType value) {
    super(NAME, ((Class) DocumentationType.class), null, value);
  }

  public LinkbaseDocumentationType() {
    super(NAME, ((Class) DocumentationType.class), null, null);
  }

}
