//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.19 at 01:31:41 PM CEST 
//


package gov.sec.ratings;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the gov.sec.ratings package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation for XML content. The Java representation of XML content can consist of schema derived interfaces and
 * classes representing the binding of schema type definitions, element declarations and model groups.  Factory methods for each of these are provided in this
 * class.
 */
@XmlRegistry
public class ObjectFactory {

  private final static QName _ROCRA_QNAME = new QName("http://xbrl.sec.gov/ratings/2015-03-31", "ROCRA");
  private final static QName _Tuple_QNAME = new QName("http://www.xbrl.org/2003/instance", "tuple");
  private final static QName _RAN_QNAME = new QName("http://xbrl.sec.gov/ratings/2015-03-31", "RAN");
  private final static QName _Item_QNAME = new QName("http://www.xbrl.org/2003/instance", "item");
  private final static QName _FCD_QNAME = new QName("http://xbrl.sec.gov/ratings/2015-03-31", "FCD");
  private final static QName _OD_QNAME = new QName("http://xbrl.sec.gov/ratings/2015-03-31", "OD");
  private final static QName _OSC_QNAME = new QName("http://xbrl.sec.gov/ratings/2015-03-31", "OSC");
  private final static QName _OIG_QNAME = new QName("http://xbrl.sec.gov/ratings/2015-03-31", "OIG");
  private final static QName _OBNAME_QNAME = new QName("http://xbrl.sec.gov/ratings/2015-03-31", "OBNAME");
  private final static QName _LEI_QNAME = new QName("http://xbrl.sec.gov/ratings/2015-03-31", "LEI");
  private final static QName _CIK_QNAME = new QName("http://xbrl.sec.gov/ratings/2015-03-31", "CIK");
  private final static QName _OI_QNAME = new QName("http://xbrl.sec.gov/ratings/2015-03-31", "OI");
  private final static QName _OIS_QNAME = new QName("http://xbrl.sec.gov/ratings/2015-03-31", "OIS");
  private final static QName _OIOS_QNAME = new QName("http://xbrl.sec.gov/ratings/2015-03-31", "OIOS");
  private final static QName _ORD_QNAME = new QName("http://xbrl.sec.gov/ratings/2015-03-31", "ORD");
  private final static QName _IP_QNAME = new QName("http://xbrl.sec.gov/ratings/2015-03-31", "IP");
  private final static QName _R_QNAME = new QName("http://xbrl.sec.gov/ratings/2015-03-31", "R");
  private final static QName _RAD_QNAME = new QName("http://xbrl.sec.gov/ratings/2015-03-31", "RAD");
  private final static QName _RAC_QNAME = new QName("http://xbrl.sec.gov/ratings/2015-03-31", "RAC");
  private final static QName _WST_QNAME = new QName("http://xbrl.sec.gov/ratings/2015-03-31", "WST");
  private final static QName _ROL_QNAME = new QName("http://xbrl.sec.gov/ratings/2015-03-31", "ROL");
  private final static QName _OAN_QNAME = new QName("http://xbrl.sec.gov/ratings/2015-03-31", "OAN");
  private final static QName _RT_QNAME = new QName("http://xbrl.sec.gov/ratings/2015-03-31", "RT");
  private final static QName _RST_QNAME = new QName("http://xbrl.sec.gov/ratings/2015-03-31", "RST");
  private final static QName _RTT_QNAME = new QName("http://xbrl.sec.gov/ratings/2015-03-31", "RTT");
  private final static QName _ISD_QNAME = new QName("http://xbrl.sec.gov/ratings/2015-03-31", "ISD");
  private final static QName _SSC_QNAME = new QName("http://xbrl.sec.gov/ratings/2015-03-31", "SSC");
  private final static QName _IG_QNAME = new QName("http://xbrl.sec.gov/ratings/2015-03-31", "IG");
  private final static QName _ISSNAME_QNAME = new QName("http://xbrl.sec.gov/ratings/2015-03-31", "ISSNAME");
  private final static QName _ISI_QNAME = new QName("http://xbrl.sec.gov/ratings/2015-03-31", "ISI");
  private final static QName _ISIS_QNAME = new QName("http://xbrl.sec.gov/ratings/2015-03-31", "ISIS");
  private final static QName _ISIOS_QNAME = new QName("http://xbrl.sec.gov/ratings/2015-03-31", "ISIOS");
  private final static QName _IND_QNAME = new QName("http://xbrl.sec.gov/ratings/2015-03-31", "IND");
  private final static QName _OBT_QNAME = new QName("http://xbrl.sec.gov/ratings/2015-03-31", "OBT");
  private final static QName _INSTNAME_QNAME = new QName("http://xbrl.sec.gov/ratings/2015-03-31", "INSTNAME");
  private final static QName _CUSIP_QNAME = new QName("http://xbrl.sec.gov/ratings/2015-03-31", "CUSIP");
  private final static QName _INI_QNAME = new QName("http://xbrl.sec.gov/ratings/2015-03-31", "INI");
  private final static QName _INIS_QNAME = new QName("http://xbrl.sec.gov/ratings/2015-03-31", "INIS");
  private final static QName _INIOS_QNAME = new QName("http://xbrl.sec.gov/ratings/2015-03-31", "INIOS");
  private final static QName _IRTD_QNAME = new QName("http://xbrl.sec.gov/ratings/2015-03-31", "IRTD");
  private final static QName _CR_QNAME = new QName("http://xbrl.sec.gov/ratings/2015-03-31", "CR");
  private final static QName _MD_QNAME = new QName("http://xbrl.sec.gov/ratings/2015-03-31", "MD");
  private final static QName _PV_QNAME = new QName("http://xbrl.sec.gov/ratings/2015-03-31", "PV");
  private final static QName _ISUD_QNAME = new QName("http://xbrl.sec.gov/ratings/2015-03-31", "ISUD");
  private final static QName _RODC_QNAME = new QName("http://xbrl.sec.gov/ratings/2015-03-31", "RODC");
  private final static QName _INRD_QNAME = new QName("http://xbrl.sec.gov/ratings/2015-03-31", "INRD");
  private final static QName _Numerator_QNAME = new QName("http://www.xbrl.org/2003/instance", "numerator");
  private final static QName _Denominator_QNAME = new QName("http://www.xbrl.org/2003/instance", "denominator");
  private final static QName _Measure_QNAME = new QName("http://www.xbrl.org/2003/instance", "measure");
  private final static QName _SchemaRef_QNAME = new QName("http://www.xbrl.org/2003/linkbase", "schemaRef");
  private final static QName _Simple_QNAME = new QName("http://www.xbrl.org/2003/XLink", "simple");
  private final static QName _LinkbaseRef_QNAME = new QName("http://www.xbrl.org/2003/linkbase", "linkbaseRef");
  private final static QName _RoleRef_QNAME = new QName("http://www.xbrl.org/2003/linkbase", "roleRef");
  private final static QName _ArcroleRef_QNAME = new QName("http://www.xbrl.org/2003/linkbase", "arcroleRef");
  private final static QName _FootnoteLink_QNAME = new QName("http://www.xbrl.org/2003/linkbase", "footnoteLink");
  private final static QName _Extended_QNAME = new QName("http://www.xbrl.org/2003/XLink", "extended");
  private final static QName _Documentation_QNAME = new QName("http://www.xbrl.org/2003/XLink", "documentation");
  private final static QName _Loc_QNAME = new QName("http://www.xbrl.org/2003/linkbase", "loc");
  private final static QName _Locator_QNAME = new QName("http://www.xbrl.org/2003/XLink", "locator");
  private final static QName _LabelArc_QNAME = new QName("http://www.xbrl.org/2003/linkbase", "labelArc");
  private final static QName _Arc_QNAME = new QName("http://www.xbrl.org/2003/XLink", "arc");
  private final static QName _ReferenceArc_QNAME = new QName("http://www.xbrl.org/2003/linkbase", "referenceArc");
  private final static QName _DefinitionArc_QNAME = new QName("http://www.xbrl.org/2003/linkbase", "definitionArc");
  private final static QName _PresentationArc_QNAME = new QName("http://www.xbrl.org/2003/linkbase", "presentationArc");
  private final static QName _CalculationArc_QNAME = new QName("http://www.xbrl.org/2003/linkbase", "calculationArc");
  private final static QName _FootnoteArc_QNAME = new QName("http://www.xbrl.org/2003/linkbase", "footnoteArc");
  private final static QName _Label_QNAME = new QName("http://www.xbrl.org/2003/linkbase", "label");
  private final static QName _Resource_QNAME = new QName("http://www.xbrl.org/2003/XLink", "resource");
  private final static QName _Part_QNAME = new QName("http://www.xbrl.org/2003/linkbase", "part");
  private final static QName _Reference_QNAME = new QName("http://www.xbrl.org/2003/linkbase", "reference");
  private final static QName _Footnote_QNAME = new QName("http://www.xbrl.org/2003/linkbase", "footnote");
  private final static QName _PresentationLink_QNAME = new QName("http://www.xbrl.org/2003/linkbase", "presentationLink");
  private final static QName _DefinitionLink_QNAME = new QName("http://www.xbrl.org/2003/linkbase", "definitionLink");
  private final static QName _CalculationLink_QNAME = new QName("http://www.xbrl.org/2003/linkbase", "calculationLink");
  private final static QName _LabelLink_QNAME = new QName("http://www.xbrl.org/2003/linkbase", "labelLink");
  private final static QName _ReferenceLink_QNAME = new QName("http://www.xbrl.org/2003/linkbase", "referenceLink");
  private final static QName _Definition_QNAME = new QName("http://www.xbrl.org/2003/linkbase", "definition");
  private final static QName _UsedOn_QNAME = new QName("http://www.xbrl.org/2003/linkbase", "usedOn");
  private final static QName _Title_QNAME = new QName("http://www.xbrl.org/2003/XLink", "title");

  /**
   * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.sec.ratings
   */
  public ObjectFactory() {
  }

  /**
   * Create an instance of {@link ContextPeriodType }
   */
  public ContextPeriodType createContextPeriodType() {
    return new ContextPeriodType();
  }

  /**
   * Create an instance of {@link ContextEntityType }
   */
  public ContextEntityType createContextEntityType() {
    return new ContextEntityType();
  }

  /**
   * Create an instance of {@link ROCRA }
   */
  public ROCRA createROCRA() {
    return new ROCRA();
  }

  /**
   * Create an instance of {@link StringItemType }
   */
  public StringItemType createStringItemType() {
    return new StringItemType();
  }

  /**
   * Create an instance of {@link DateItemType }
   */
  public DateItemType createDateItemType() {
    return new DateItemType();
  }

  /**
   * Create an instance of {@link OD }
   */
  public OD createOD() {
    return new OD();
  }

  /**
   * Create an instance of {@link SECCategoryItemType }
   */
  public SECCategoryItemType createSECCategoryItemType() {
    return new SECCategoryItemType();
  }

  /**
   * Create an instance of {@link LeiItemType }
   */
  public LeiItemType createLeiItemType() {
    return new LeiItemType();
  }

  /**
   * Create an instance of {@link CentralIndexKey2ItemType }
   */
  public CentralIndexKey2ItemType createCentralIndexKey2ItemType() {
    return new CentralIndexKey2ItemType();
  }

  /**
   * Create an instance of {@link IssuerIdentifierSchemeItemType }
   */
  public IssuerIdentifierSchemeItemType createIssuerIdentifierSchemeItemType() {
    return new IssuerIdentifierSchemeItemType();
  }

  /**
   * Create an instance of {@link RatingDetailType }
   */
  public RatingDetailType createRatingDetailType() {
    return new RatingDetailType();
  }

  /**
   * Create an instance of {@link BooleanItemType }
   */
  public BooleanItemType createBooleanItemType() {
    return new BooleanItemType();
  }

  /**
   * Create an instance of {@link RAC }
   */
  public RAC createRAC() {
    return new RAC();
  }

  /**
   * Create an instance of {@link ISD }
   */
  public ISD createISD() {
    return new ISD();
  }

  /**
   * Create an instance of {@link IND }
   */
  public IND createIND() {
    return new IND();
  }

  /**
   * Create an instance of {@link OBT }
   */
  public OBT createOBT() {
    return new OBT();
  }

  /**
   * Create an instance of {@link CusipItemType }
   */
  public CusipItemType createCusipItemType() {
    return new CusipItemType();
  }

  /**
   * Create an instance of {@link INIS }
   */
  public INIS createINIS() {
    return new INIS();
  }

  /**
   * Create an instance of {@link PureItemType }
   */
  public PureItemType createPureItemType() {
    return new PureItemType();
  }

  /**
   * Create an instance of {@link MonetaryItemType }
   */
  public MonetaryItemType createMonetaryItemType() {
    return new MonetaryItemType();
  }

  /**
   * Create an instance of {@link Segment }
   */
  public Segment createSegment() {
    return new Segment();
  }

  /**
   * Create an instance of {@link Context }
   */
  public Context createContext() {
    return new Context();
  }

  /**
   * Create an instance of {@link ContextScenarioType }
   */
  public ContextScenarioType createContextScenarioType() {
    return new ContextScenarioType();
  }

  /**
   * Create an instance of {@link Divide }
   */
  public Divide createDivide() {
    return new Divide();
  }

  /**
   * Create an instance of {@link MeasuresType }
   */
  public MeasuresType createMeasuresType() {
    return new MeasuresType();
  }

  /**
   * Create an instance of {@link Unit }
   */
  public Unit createUnit() {
    return new Unit();
  }

  /**
   * Create an instance of {@link Xbrl }
   */
  public Xbrl createXbrl() {
    return new Xbrl();
  }

  /**
   * Create an instance of {@link SimpleType }
   */
  public SimpleType createSimpleType() {
    return new SimpleType();
  }

  /**
   * Create an instance of {@link LinkbaseRef }
   */
  public LinkbaseRef createLinkbaseRef() {
    return new LinkbaseRef();
  }

  /**
   * Create an instance of {@link RoleRef }
   */
  public RoleRef createRoleRef() {
    return new RoleRef();
  }

  /**
   * Create an instance of {@link ArcroleRef }
   */
  public ArcroleRef createArcroleRef() {
    return new ArcroleRef();
  }

  /**
   * Create an instance of {@link FootnoteLink }
   */
  public FootnoteLink createFootnoteLink() {
    return new FootnoteLink();
  }

  /**
   * Create an instance of {@link ExtendedType }
   */
  public ExtendedType createExtendedType() {
    return new ExtendedType();
  }

  /**
   * Create an instance of {@link DecimalItemType }
   */
  public DecimalItemType createDecimalItemType() {
    return new DecimalItemType();
  }

  /**
   * Create an instance of {@link FloatItemType }
   */
  public FloatItemType createFloatItemType() {
    return new FloatItemType();
  }

  /**
   * Create an instance of {@link DoubleItemType }
   */
  public DoubleItemType createDoubleItemType() {
    return new DoubleItemType();
  }

  /**
   * Create an instance of {@link SharesItemType }
   */
  public SharesItemType createSharesItemType() {
    return new SharesItemType();
  }

  /**
   * Create an instance of {@link FractionItemType }
   */
  public FractionItemType createFractionItemType() {
    return new FractionItemType();
  }

  /**
   * Create an instance of {@link IntegerItemType }
   */
  public IntegerItemType createIntegerItemType() {
    return new IntegerItemType();
  }

  /**
   * Create an instance of {@link NonPositiveIntegerItemType }
   */
  public NonPositiveIntegerItemType createNonPositiveIntegerItemType() {
    return new NonPositiveIntegerItemType();
  }

  /**
   * Create an instance of {@link NegativeIntegerItemType }
   */
  public NegativeIntegerItemType createNegativeIntegerItemType() {
    return new NegativeIntegerItemType();
  }

  /**
   * Create an instance of {@link LongItemType }
   */
  public LongItemType createLongItemType() {
    return new LongItemType();
  }

  /**
   * Create an instance of {@link IntItemType }
   */
  public IntItemType createIntItemType() {
    return new IntItemType();
  }

  /**
   * Create an instance of {@link ShortItemType }
   */
  public ShortItemType createShortItemType() {
    return new ShortItemType();
  }

  /**
   * Create an instance of {@link ByteItemType }
   */
  public ByteItemType createByteItemType() {
    return new ByteItemType();
  }

  /**
   * Create an instance of {@link NonNegativeIntegerItemType }
   */
  public NonNegativeIntegerItemType createNonNegativeIntegerItemType() {
    return new NonNegativeIntegerItemType();
  }

  /**
   * Create an instance of {@link UnsignedLongItemType }
   */
  public UnsignedLongItemType createUnsignedLongItemType() {
    return new UnsignedLongItemType();
  }

  /**
   * Create an instance of {@link UnsignedIntItemType }
   */
  public UnsignedIntItemType createUnsignedIntItemType() {
    return new UnsignedIntItemType();
  }

  /**
   * Create an instance of {@link UnsignedShortItemType }
   */
  public UnsignedShortItemType createUnsignedShortItemType() {
    return new UnsignedShortItemType();
  }

  /**
   * Create an instance of {@link UnsignedByteItemType }
   */
  public UnsignedByteItemType createUnsignedByteItemType() {
    return new UnsignedByteItemType();
  }

  /**
   * Create an instance of {@link PositiveIntegerItemType }
   */
  public PositiveIntegerItemType createPositiveIntegerItemType() {
    return new PositiveIntegerItemType();
  }

  /**
   * Create an instance of {@link HexBinaryItemType }
   */
  public HexBinaryItemType createHexBinaryItemType() {
    return new HexBinaryItemType();
  }

  /**
   * Create an instance of {@link Base64BinaryItemType }
   */
  public Base64BinaryItemType createBase64BinaryItemType() {
    return new Base64BinaryItemType();
  }

  /**
   * Create an instance of {@link AnyURIItemType }
   */
  public AnyURIItemType createAnyURIItemType() {
    return new AnyURIItemType();
  }

  /**
   * Create an instance of {@link QNameItemType }
   */
  public QNameItemType createQNameItemType() {
    return new QNameItemType();
  }

  /**
   * Create an instance of {@link DurationItemType }
   */
  public DurationItemType createDurationItemType() {
    return new DurationItemType();
  }

  /**
   * Create an instance of {@link DateTimeItemType }
   */
  public DateTimeItemType createDateTimeItemType() {
    return new DateTimeItemType();
  }

  /**
   * Create an instance of {@link TimeItemType }
   */
  public TimeItemType createTimeItemType() {
    return new TimeItemType();
  }

  /**
   * Create an instance of {@link GYearMonthItemType }
   */
  public GYearMonthItemType createGYearMonthItemType() {
    return new GYearMonthItemType();
  }

  /**
   * Create an instance of {@link GYearItemType }
   */
  public GYearItemType createGYearItemType() {
    return new GYearItemType();
  }

  /**
   * Create an instance of {@link GMonthDayItemType }
   */
  public GMonthDayItemType createGMonthDayItemType() {
    return new GMonthDayItemType();
  }

  /**
   * Create an instance of {@link GDayItemType }
   */
  public GDayItemType createGDayItemType() {
    return new GDayItemType();
  }

  /**
   * Create an instance of {@link GMonthItemType }
   */
  public GMonthItemType createGMonthItemType() {
    return new GMonthItemType();
  }

  /**
   * Create an instance of {@link NormalizedStringItemType }
   */
  public NormalizedStringItemType createNormalizedStringItemType() {
    return new NormalizedStringItemType();
  }

  /**
   * Create an instance of {@link TokenItemType }
   */
  public TokenItemType createTokenItemType() {
    return new TokenItemType();
  }

  /**
   * Create an instance of {@link LanguageItemType }
   */
  public LanguageItemType createLanguageItemType() {
    return new LanguageItemType();
  }

  /**
   * Create an instance of {@link NameItemType }
   */
  public NameItemType createNameItemType() {
    return new NameItemType();
  }

  /**
   * Create an instance of {@link NCNameItemType }
   */
  public NCNameItemType createNCNameItemType() {
    return new NCNameItemType();
  }

  /**
   * Create an instance of {@link DocumentationType }
   */
  public DocumentationType createDocumentationType() {
    return new DocumentationType();
  }

  /**
   * Create an instance of {@link LocatorType }
   */
  public LocatorType createLocatorType() {
    return new LocatorType();
  }

  /**
   * Create an instance of {@link ArcType }
   */
  public ArcType createArcType() {
    return new ArcType();
  }

  /**
   * Create an instance of {@link PresentationArc }
   */
  public PresentationArc createPresentationArc() {
    return new PresentationArc();
  }

  /**
   * Create an instance of {@link CalculationArc }
   */
  public CalculationArc createCalculationArc() {
    return new CalculationArc();
  }

  /**
   * Create an instance of {@link Label }
   */
  public Label createLabel() {
    return new Label();
  }

  /**
   * Create an instance of {@link ResourceType }
   */
  public ResourceType createResourceType() {
    return new ResourceType();
  }

  /**
   * Create an instance of {@link Reference }
   */
  public Reference createReference() {
    return new Reference();
  }

  /**
   * Create an instance of {@link Footnote }
   */
  public Footnote createFootnote() {
    return new Footnote();
  }

  /**
   * Create an instance of {@link PresentationLink }
   */
  public PresentationLink createPresentationLink() {
    return new PresentationLink();
  }

  /**
   * Create an instance of {@link DefinitionLink }
   */
  public DefinitionLink createDefinitionLink() {
    return new DefinitionLink();
  }

  /**
   * Create an instance of {@link CalculationLink }
   */
  public CalculationLink createCalculationLink() {
    return new CalculationLink();
  }

  /**
   * Create an instance of {@link LabelLink }
   */
  public LabelLink createLabelLink() {
    return new LabelLink();
  }

  /**
   * Create an instance of {@link ReferenceLink }
   */
  public ReferenceLink createReferenceLink() {
    return new ReferenceLink();
  }

  /**
   * Create an instance of {@link Linkbase }
   */
  public Linkbase createLinkbase() {
    return new Linkbase();
  }

  /**
   * Create an instance of {@link RoleType }
   */
  public RoleType createRoleType() {
    return new RoleType();
  }

  /**
   * Create an instance of {@link ArcroleType }
   */
  public ArcroleType createArcroleType() {
    return new ArcroleType();
  }

  /**
   * Create an instance of {@link TitleType }
   */
  public TitleType createTitleType() {
    return new TitleType();
  }

  /**
   * Create an instance of {@link ContextPeriodType.Forever }
   */
  public ContextPeriodType.Forever createContextPeriodTypeForever() {
    return new ContextPeriodType.Forever();
  }

  /**
   * Create an instance of {@link ContextEntityType.Identifier }
   */
  public ContextEntityType.Identifier createContextEntityTypeIdentifier() {
    return new ContextEntityType.Identifier();
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link ROCRA }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link ROCRA }{@code >}
   */
  @XmlElementDecl(namespace = "http://xbrl.sec.gov/ratings/2015-03-31", name = "ROCRA", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "tuple")
  public JAXBElement<ROCRA> createROCRA(ROCRA value) {
    return new JAXBElement<ROCRA>(_ROCRA_QNAME, ROCRA.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
   */
  @XmlElementDecl(namespace = "http://www.xbrl.org/2003/instance", name = "tuple")
  public JAXBElement<Object> createTuple(Object value) {
    return new JAXBElement<Object>(_Tuple_QNAME, Object.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link StringItemType }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link StringItemType }{@code >}
   */
  @XmlElementDecl(namespace = "http://xbrl.sec.gov/ratings/2015-03-31", name = "RAN", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
  public JAXBElement<StringItemType> createRAN(StringItemType value) {
    return new JAXBElement<StringItemType>(_RAN_QNAME, StringItemType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
   */
  @XmlElementDecl(namespace = "http://www.xbrl.org/2003/instance", name = "item")
  public JAXBElement<Object> createItem(Object value) {
    return new JAXBElement<Object>(_Item_QNAME, Object.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link DateItemType }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link DateItemType }{@code >}
   */
  @XmlElementDecl(namespace = "http://xbrl.sec.gov/ratings/2015-03-31", name = "FCD", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
  public JAXBElement<DateItemType> createFCD(DateItemType value) {
    return new JAXBElement<DateItemType>(_FCD_QNAME, DateItemType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link OD }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link OD }{@code >}
   */
  @XmlElementDecl(namespace = "http://xbrl.sec.gov/ratings/2015-03-31", name = "OD", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "tuple")
  public JAXBElement<OD> createOD(OD value) {
    return new JAXBElement<OD>(_OD_QNAME, OD.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link SECCategoryItemType }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link SECCategoryItemType }{@code >}
   */
  @XmlElementDecl(namespace = "http://xbrl.sec.gov/ratings/2015-03-31", name = "OSC", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
  public JAXBElement<SECCategoryItemType> createOSC(SECCategoryItemType value) {
    return new JAXBElement<SECCategoryItemType>(_OSC_QNAME, SECCategoryItemType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link StringItemType }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link StringItemType }{@code >}
   */
  @XmlElementDecl(namespace = "http://xbrl.sec.gov/ratings/2015-03-31", name = "OIG", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
  public JAXBElement<StringItemType> createOIG(StringItemType value) {
    return new JAXBElement<StringItemType>(_OIG_QNAME, StringItemType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link StringItemType }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link StringItemType }{@code >}
   */
  @XmlElementDecl(namespace = "http://xbrl.sec.gov/ratings/2015-03-31", name = "OBNAME", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
  public JAXBElement<StringItemType> createOBNAME(StringItemType value) {
    return new JAXBElement<StringItemType>(_OBNAME_QNAME, StringItemType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link LeiItemType }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link LeiItemType }{@code >}
   */
  @XmlElementDecl(namespace = "http://xbrl.sec.gov/ratings/2015-03-31", name = "LEI", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
  public JAXBElement<LeiItemType> createLEI(LeiItemType value) {
    return new JAXBElement<LeiItemType>(_LEI_QNAME, LeiItemType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link CentralIndexKey2ItemType }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link CentralIndexKey2ItemType }{@code >}
   */
  @XmlElementDecl(namespace = "http://xbrl.sec.gov/ratings/2015-03-31", name = "CIK", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
  public JAXBElement<CentralIndexKey2ItemType> createCIK(CentralIndexKey2ItemType value) {
    return new JAXBElement<CentralIndexKey2ItemType>(_CIK_QNAME, CentralIndexKey2ItemType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link StringItemType }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link StringItemType }{@code >}
   */
  @XmlElementDecl(namespace = "http://xbrl.sec.gov/ratings/2015-03-31", name = "OI", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
  public JAXBElement<StringItemType> createOI(StringItemType value) {
    return new JAXBElement<StringItemType>(_OI_QNAME, StringItemType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link IssuerIdentifierSchemeItemType }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link IssuerIdentifierSchemeItemType }{@code >}
   */
  @XmlElementDecl(namespace = "http://xbrl.sec.gov/ratings/2015-03-31", name = "OIS", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
  public JAXBElement<IssuerIdentifierSchemeItemType> createOIS(IssuerIdentifierSchemeItemType value) {
    return new JAXBElement<IssuerIdentifierSchemeItemType>(_OIS_QNAME, IssuerIdentifierSchemeItemType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link StringItemType }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link StringItemType }{@code >}
   */
  @XmlElementDecl(namespace = "http://xbrl.sec.gov/ratings/2015-03-31", name = "OIOS", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
  public JAXBElement<StringItemType> createOIOS(StringItemType value) {
    return new JAXBElement<StringItemType>(_OIOS_QNAME, StringItemType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link RatingDetailType }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link RatingDetailType }{@code >}
   */
  @XmlElementDecl(namespace = "http://xbrl.sec.gov/ratings/2015-03-31", name = "ORD", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "tuple")
  public JAXBElement<RatingDetailType> createORD(RatingDetailType value) {
    return new JAXBElement<RatingDetailType>(_ORD_QNAME, RatingDetailType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link BooleanItemType }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link BooleanItemType }{@code >}
   */
  @XmlElementDecl(namespace = "http://xbrl.sec.gov/ratings/2015-03-31", name = "IP", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
  public JAXBElement<BooleanItemType> createIP(BooleanItemType value) {
    return new JAXBElement<BooleanItemType>(_IP_QNAME, BooleanItemType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link StringItemType }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link StringItemType }{@code >}
   */
  @XmlElementDecl(namespace = "http://xbrl.sec.gov/ratings/2015-03-31", name = "R", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
  public JAXBElement<StringItemType> createR(StringItemType value) {
    return new JAXBElement<StringItemType>(_R_QNAME, StringItemType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link DateItemType }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link DateItemType }{@code >}
   */
  @XmlElementDecl(namespace = "http://xbrl.sec.gov/ratings/2015-03-31", name = "RAD", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
  public JAXBElement<DateItemType> createRAD(DateItemType value) {
    return new JAXBElement<DateItemType>(_RAD_QNAME, DateItemType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link RAC }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link RAC }{@code >}
   */
  @XmlElementDecl(namespace = "http://xbrl.sec.gov/ratings/2015-03-31", name = "RAC", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
  public JAXBElement<RAC> createRAC(RAC value) {
    return new JAXBElement<RAC>(_RAC_QNAME, RAC.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link StringItemType }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link StringItemType }{@code >}
   */
  @XmlElementDecl(namespace = "http://xbrl.sec.gov/ratings/2015-03-31", name = "WST", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
  public JAXBElement<StringItemType> createWST(StringItemType value) {
    return new JAXBElement<StringItemType>(_WST_QNAME, StringItemType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link StringItemType }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link StringItemType }{@code >}
   */
  @XmlElementDecl(namespace = "http://xbrl.sec.gov/ratings/2015-03-31", name = "ROL", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
  public JAXBElement<StringItemType> createROL(StringItemType value) {
    return new JAXBElement<StringItemType>(_ROL_QNAME, StringItemType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link StringItemType }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link StringItemType }{@code >}
   */
  @XmlElementDecl(namespace = "http://xbrl.sec.gov/ratings/2015-03-31", name = "OAN", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
  public JAXBElement<StringItemType> createOAN(StringItemType value) {
    return new JAXBElement<StringItemType>(_OAN_QNAME, StringItemType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link StringItemType }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link StringItemType }{@code >}
   */
  @XmlElementDecl(namespace = "http://xbrl.sec.gov/ratings/2015-03-31", name = "RT", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
  public JAXBElement<StringItemType> createRT(StringItemType value) {
    return new JAXBElement<StringItemType>(_RT_QNAME, StringItemType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link StringItemType }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link StringItemType }{@code >}
   */
  @XmlElementDecl(namespace = "http://xbrl.sec.gov/ratings/2015-03-31", name = "RST", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
  public JAXBElement<StringItemType> createRST(StringItemType value) {
    return new JAXBElement<StringItemType>(_RST_QNAME, StringItemType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link StringItemType }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link StringItemType }{@code >}
   */
  @XmlElementDecl(namespace = "http://xbrl.sec.gov/ratings/2015-03-31", name = "RTT", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
  public JAXBElement<StringItemType> createRTT(StringItemType value) {
    return new JAXBElement<StringItemType>(_RTT_QNAME, StringItemType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link ISD }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link ISD }{@code >}
   */
  @XmlElementDecl(namespace = "http://xbrl.sec.gov/ratings/2015-03-31", name = "ISD", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "tuple")
  public JAXBElement<ISD> createISD(ISD value) {
    return new JAXBElement<ISD>(_ISD_QNAME, ISD.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link SECCategoryItemType }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link SECCategoryItemType }{@code >}
   */
  @XmlElementDecl(namespace = "http://xbrl.sec.gov/ratings/2015-03-31", name = "SSC", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
  public JAXBElement<SECCategoryItemType> createSSC(SECCategoryItemType value) {
    return new JAXBElement<SECCategoryItemType>(_SSC_QNAME, SECCategoryItemType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link StringItemType }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link StringItemType }{@code >}
   */
  @XmlElementDecl(namespace = "http://xbrl.sec.gov/ratings/2015-03-31", name = "IG", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
  public JAXBElement<StringItemType> createIG(StringItemType value) {
    return new JAXBElement<StringItemType>(_IG_QNAME, StringItemType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link StringItemType }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link StringItemType }{@code >}
   */
  @XmlElementDecl(namespace = "http://xbrl.sec.gov/ratings/2015-03-31", name = "ISSNAME", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
  public JAXBElement<StringItemType> createISSNAME(StringItemType value) {
    return new JAXBElement<StringItemType>(_ISSNAME_QNAME, StringItemType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link StringItemType }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link StringItemType }{@code >}
   */
  @XmlElementDecl(namespace = "http://xbrl.sec.gov/ratings/2015-03-31", name = "ISI", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
  public JAXBElement<StringItemType> createISI(StringItemType value) {
    return new JAXBElement<StringItemType>(_ISI_QNAME, StringItemType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link IssuerIdentifierSchemeItemType }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link IssuerIdentifierSchemeItemType }{@code >}
   */
  @XmlElementDecl(namespace = "http://xbrl.sec.gov/ratings/2015-03-31", name = "ISIS", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
  public JAXBElement<IssuerIdentifierSchemeItemType> createISIS(IssuerIdentifierSchemeItemType value) {
    return new JAXBElement<IssuerIdentifierSchemeItemType>(_ISIS_QNAME, IssuerIdentifierSchemeItemType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link StringItemType }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link StringItemType }{@code >}
   */
  @XmlElementDecl(namespace = "http://xbrl.sec.gov/ratings/2015-03-31", name = "ISIOS", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
  public JAXBElement<StringItemType> createISIOS(StringItemType value) {
    return new JAXBElement<StringItemType>(_ISIOS_QNAME, StringItemType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link IND }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link IND }{@code >}
   */
  @XmlElementDecl(namespace = "http://xbrl.sec.gov/ratings/2015-03-31", name = "IND", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "tuple")
  public JAXBElement<IND> createIND(IND value) {
    return new JAXBElement<IND>(_IND_QNAME, IND.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link OBT }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link OBT }{@code >}
   */
  @XmlElementDecl(namespace = "http://xbrl.sec.gov/ratings/2015-03-31", name = "OBT", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
  public JAXBElement<OBT> createOBT(OBT value) {
    return new JAXBElement<OBT>(_OBT_QNAME, OBT.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link StringItemType }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link StringItemType }{@code >}
   */
  @XmlElementDecl(namespace = "http://xbrl.sec.gov/ratings/2015-03-31", name = "INSTNAME", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
  public JAXBElement<StringItemType> createINSTNAME(StringItemType value) {
    return new JAXBElement<StringItemType>(_INSTNAME_QNAME, StringItemType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link CusipItemType }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link CusipItemType }{@code >}
   */
  @XmlElementDecl(namespace = "http://xbrl.sec.gov/ratings/2015-03-31", name = "CUSIP", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
  public JAXBElement<CusipItemType> createCUSIP(CusipItemType value) {
    return new JAXBElement<CusipItemType>(_CUSIP_QNAME, CusipItemType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link StringItemType }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link StringItemType }{@code >}
   */
  @XmlElementDecl(namespace = "http://xbrl.sec.gov/ratings/2015-03-31", name = "INI", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
  public JAXBElement<StringItemType> createINI(StringItemType value) {
    return new JAXBElement<StringItemType>(_INI_QNAME, StringItemType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link INIS }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link INIS }{@code >}
   */
  @XmlElementDecl(namespace = "http://xbrl.sec.gov/ratings/2015-03-31", name = "INIS", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
  public JAXBElement<INIS> createINIS(INIS value) {
    return new JAXBElement<INIS>(_INIS_QNAME, INIS.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link StringItemType }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link StringItemType }{@code >}
   */
  @XmlElementDecl(namespace = "http://xbrl.sec.gov/ratings/2015-03-31", name = "INIOS", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
  public JAXBElement<StringItemType> createINIOS(StringItemType value) {
    return new JAXBElement<StringItemType>(_INIOS_QNAME, StringItemType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link StringItemType }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link StringItemType }{@code >}
   */
  @XmlElementDecl(namespace = "http://xbrl.sec.gov/ratings/2015-03-31", name = "IRTD", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
  public JAXBElement<StringItemType> createIRTD(StringItemType value) {
    return new JAXBElement<StringItemType>(_IRTD_QNAME, StringItemType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link PureItemType }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link PureItemType }{@code >}
   */
  @XmlElementDecl(namespace = "http://xbrl.sec.gov/ratings/2015-03-31", name = "CR", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
  public JAXBElement<PureItemType> createCR(PureItemType value) {
    return new JAXBElement<PureItemType>(_CR_QNAME, PureItemType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link DateItemType }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link DateItemType }{@code >}
   */
  @XmlElementDecl(namespace = "http://xbrl.sec.gov/ratings/2015-03-31", name = "MD", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
  public JAXBElement<DateItemType> createMD(DateItemType value) {
    return new JAXBElement<DateItemType>(_MD_QNAME, DateItemType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link MonetaryItemType }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link MonetaryItemType }{@code >}
   */
  @XmlElementDecl(namespace = "http://xbrl.sec.gov/ratings/2015-03-31", name = "PV", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
  public JAXBElement<MonetaryItemType> createPV(MonetaryItemType value) {
    return new JAXBElement<MonetaryItemType>(_PV_QNAME, MonetaryItemType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link DateItemType }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link DateItemType }{@code >}
   */
  @XmlElementDecl(namespace = "http://xbrl.sec.gov/ratings/2015-03-31", name = "ISUD", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
  public JAXBElement<DateItemType> createISUD(DateItemType value) {
    return new JAXBElement<DateItemType>(_ISUD_QNAME, DateItemType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link StringItemType }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link StringItemType }{@code >}
   */
  @XmlElementDecl(namespace = "http://xbrl.sec.gov/ratings/2015-03-31", name = "RODC", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
  public JAXBElement<StringItemType> createRODC(StringItemType value) {
    return new JAXBElement<StringItemType>(_RODC_QNAME, StringItemType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link RatingDetailType }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link RatingDetailType }{@code >}
   */
  @XmlElementDecl(namespace = "http://xbrl.sec.gov/ratings/2015-03-31", name = "INRD", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "tuple")
  public JAXBElement<RatingDetailType> createINRD(RatingDetailType value) {
    return new JAXBElement<RatingDetailType>(_INRD_QNAME, RatingDetailType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
   */
  @XmlElementDecl(namespace = "http://www.xbrl.org/2003/instance", name = "numerator")
  public JAXBElement<BigDecimal> createNumerator(BigDecimal value) {
    return new JAXBElement<BigDecimal>(_Numerator_QNAME, BigDecimal.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
   */
  @XmlElementDecl(namespace = "http://www.xbrl.org/2003/instance", name = "denominator")
  public JAXBElement<String> createDenominator(String value) {
    return new JAXBElement<String>(_Denominator_QNAME, String.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link QName }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link QName }{@code >}
   */
  @XmlElementDecl(namespace = "http://www.xbrl.org/2003/instance", name = "measure")
  public JAXBElement<QName> createMeasure(QName value) {
    return new JAXBElement<QName>(_Measure_QNAME, QName.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link SimpleType }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link SimpleType }{@code >}
   */
  @XmlElementDecl(namespace = "http://www.xbrl.org/2003/linkbase", name = "schemaRef", substitutionHeadNamespace = "http://www.xbrl.org/2003/XLink", substitutionHeadName = "simple")
  public JAXBElement<SimpleType> createSchemaRef(SimpleType value) {
    return new JAXBElement<SimpleType>(_SchemaRef_QNAME, SimpleType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link SimpleType }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link SimpleType }{@code >}
   */
  @XmlElementDecl(namespace = "http://www.xbrl.org/2003/XLink", name = "simple")
  public JAXBElement<SimpleType> createSimple(SimpleType value) {
    return new JAXBElement<SimpleType>(_Simple_QNAME, SimpleType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link LinkbaseRef }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link LinkbaseRef }{@code >}
   */
  @XmlElementDecl(namespace = "http://www.xbrl.org/2003/linkbase", name = "linkbaseRef", substitutionHeadNamespace = "http://www.xbrl.org/2003/XLink", substitutionHeadName = "simple")
  public JAXBElement<LinkbaseRef> createLinkbaseRef(LinkbaseRef value) {
    return new JAXBElement<LinkbaseRef>(_LinkbaseRef_QNAME, LinkbaseRef.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link RoleRef }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link RoleRef }{@code >}
   */
  @XmlElementDecl(namespace = "http://www.xbrl.org/2003/linkbase", name = "roleRef", substitutionHeadNamespace = "http://www.xbrl.org/2003/XLink", substitutionHeadName = "simple")
  public JAXBElement<RoleRef> createRoleRef(RoleRef value) {
    return new JAXBElement<RoleRef>(_RoleRef_QNAME, RoleRef.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link ArcroleRef }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link ArcroleRef }{@code >}
   */
  @XmlElementDecl(namespace = "http://www.xbrl.org/2003/linkbase", name = "arcroleRef", substitutionHeadNamespace = "http://www.xbrl.org/2003/XLink", substitutionHeadName = "simple")
  public JAXBElement<ArcroleRef> createArcroleRef(ArcroleRef value) {
    return new JAXBElement<ArcroleRef>(_ArcroleRef_QNAME, ArcroleRef.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link FootnoteLink }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link FootnoteLink }{@code >}
   */
  @XmlElementDecl(namespace = "http://www.xbrl.org/2003/linkbase", name = "footnoteLink", substitutionHeadNamespace = "http://www.xbrl.org/2003/XLink", substitutionHeadName = "extended")
  public JAXBElement<FootnoteLink> createFootnoteLink(FootnoteLink value) {
    return new JAXBElement<FootnoteLink>(_FootnoteLink_QNAME, FootnoteLink.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link ExtendedType }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link ExtendedType }{@code >}
   */
  @XmlElementDecl(namespace = "http://www.xbrl.org/2003/XLink", name = "extended")
  public JAXBElement<ExtendedType> createExtended(ExtendedType value) {
    return new JAXBElement<ExtendedType>(_Extended_QNAME, ExtendedType.class, null, value);
  }

  /**
   * Create an instance of {@link LinkbaseDocumentationType }
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link LinkbaseDocumentationType }
   */
  @XmlElementDecl(namespace = "http://www.xbrl.org/2003/linkbase", name = "documentation", substitutionHeadNamespace = "http://www.xbrl.org/2003/XLink", substitutionHeadName = "documentation")
  public LinkbaseDocumentationType createLinkbaseDocumentationType(DocumentationType value) {
    return new LinkbaseDocumentationType(value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link DocumentationType }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link DocumentationType }{@code >}
   */
  @XmlElementDecl(namespace = "http://www.xbrl.org/2003/XLink", name = "documentation")
  public JAXBElement<DocumentationType> createDocumentation(DocumentationType value) {
    return new JAXBElement<DocumentationType>(_Documentation_QNAME, DocumentationType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link LocatorType }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link LocatorType }{@code >}
   */
  @XmlElementDecl(namespace = "http://www.xbrl.org/2003/linkbase", name = "loc", substitutionHeadNamespace = "http://www.xbrl.org/2003/XLink", substitutionHeadName = "locator")
  public JAXBElement<LocatorType> createLoc(LocatorType value) {
    return new JAXBElement<LocatorType>(_Loc_QNAME, LocatorType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link LocatorType }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link LocatorType }{@code >}
   */
  @XmlElementDecl(namespace = "http://www.xbrl.org/2003/XLink", name = "locator")
  public JAXBElement<LocatorType> createLocator(LocatorType value) {
    return new JAXBElement<LocatorType>(_Locator_QNAME, LocatorType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link ArcType }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link ArcType }{@code >}
   */
  @XmlElementDecl(namespace = "http://www.xbrl.org/2003/linkbase", name = "labelArc", substitutionHeadNamespace = "http://www.xbrl.org/2003/XLink", substitutionHeadName = "arc")
  public JAXBElement<ArcType> createLabelArc(ArcType value) {
    return new JAXBElement<ArcType>(_LabelArc_QNAME, ArcType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link ArcType }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link ArcType }{@code >}
   */
  @XmlElementDecl(namespace = "http://www.xbrl.org/2003/XLink", name = "arc")
  public JAXBElement<ArcType> createArc(ArcType value) {
    return new JAXBElement<ArcType>(_Arc_QNAME, ArcType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link ArcType }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link ArcType }{@code >}
   */
  @XmlElementDecl(namespace = "http://www.xbrl.org/2003/linkbase", name = "referenceArc", substitutionHeadNamespace = "http://www.xbrl.org/2003/XLink", substitutionHeadName = "arc")
  public JAXBElement<ArcType> createReferenceArc(ArcType value) {
    return new JAXBElement<ArcType>(_ReferenceArc_QNAME, ArcType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link ArcType }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link ArcType }{@code >}
   */
  @XmlElementDecl(namespace = "http://www.xbrl.org/2003/linkbase", name = "definitionArc", substitutionHeadNamespace = "http://www.xbrl.org/2003/XLink", substitutionHeadName = "arc")
  public JAXBElement<ArcType> createDefinitionArc(ArcType value) {
    return new JAXBElement<ArcType>(_DefinitionArc_QNAME, ArcType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link PresentationArc }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link PresentationArc }{@code >}
   */
  @XmlElementDecl(namespace = "http://www.xbrl.org/2003/linkbase", name = "presentationArc", substitutionHeadNamespace = "http://www.xbrl.org/2003/XLink", substitutionHeadName = "arc")
  public JAXBElement<PresentationArc> createPresentationArc(PresentationArc value) {
    return new JAXBElement<PresentationArc>(_PresentationArc_QNAME, PresentationArc.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link CalculationArc }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link CalculationArc }{@code >}
   */
  @XmlElementDecl(namespace = "http://www.xbrl.org/2003/linkbase", name = "calculationArc", substitutionHeadNamespace = "http://www.xbrl.org/2003/XLink", substitutionHeadName = "arc")
  public JAXBElement<CalculationArc> createCalculationArc(CalculationArc value) {
    return new JAXBElement<CalculationArc>(_CalculationArc_QNAME, CalculationArc.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link ArcType }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link ArcType }{@code >}
   */
  @XmlElementDecl(namespace = "http://www.xbrl.org/2003/linkbase", name = "footnoteArc", substitutionHeadNamespace = "http://www.xbrl.org/2003/XLink", substitutionHeadName = "arc")
  public JAXBElement<ArcType> createFootnoteArc(ArcType value) {
    return new JAXBElement<ArcType>(_FootnoteArc_QNAME, ArcType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link Label }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link Label }{@code >}
   */
  @XmlElementDecl(namespace = "http://www.xbrl.org/2003/linkbase", name = "label", substitutionHeadNamespace = "http://www.xbrl.org/2003/XLink", substitutionHeadName = "resource")
  public JAXBElement<Label> createLabel(Label value) {
    return new JAXBElement<Label>(_Label_QNAME, Label.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link ResourceType }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link ResourceType }{@code >}
   */
  @XmlElementDecl(namespace = "http://www.xbrl.org/2003/XLink", name = "resource")
  public JAXBElement<ResourceType> createResource(ResourceType value) {
    return new JAXBElement<ResourceType>(_Resource_QNAME, ResourceType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
   */
  @XmlElementDecl(namespace = "http://www.xbrl.org/2003/linkbase", name = "part")
  public JAXBElement<Object> createPart(Object value) {
    return new JAXBElement<Object>(_Part_QNAME, Object.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link Reference }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link Reference }{@code >}
   */
  @XmlElementDecl(namespace = "http://www.xbrl.org/2003/linkbase", name = "reference", substitutionHeadNamespace = "http://www.xbrl.org/2003/XLink", substitutionHeadName = "resource")
  public JAXBElement<Reference> createReference(Reference value) {
    return new JAXBElement<Reference>(_Reference_QNAME, Reference.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link Footnote }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link Footnote }{@code >}
   */
  @XmlElementDecl(namespace = "http://www.xbrl.org/2003/linkbase", name = "footnote", substitutionHeadNamespace = "http://www.xbrl.org/2003/XLink", substitutionHeadName = "resource")
  public JAXBElement<Footnote> createFootnote(Footnote value) {
    return new JAXBElement<Footnote>(_Footnote_QNAME, Footnote.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link PresentationLink }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link PresentationLink }{@code >}
   */
  @XmlElementDecl(namespace = "http://www.xbrl.org/2003/linkbase", name = "presentationLink", substitutionHeadNamespace = "http://www.xbrl.org/2003/XLink", substitutionHeadName = "extended")
  public JAXBElement<PresentationLink> createPresentationLink(PresentationLink value) {
    return new JAXBElement<PresentationLink>(_PresentationLink_QNAME, PresentationLink.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link DefinitionLink }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link DefinitionLink }{@code >}
   */
  @XmlElementDecl(namespace = "http://www.xbrl.org/2003/linkbase", name = "definitionLink", substitutionHeadNamespace = "http://www.xbrl.org/2003/XLink", substitutionHeadName = "extended")
  public JAXBElement<DefinitionLink> createDefinitionLink(DefinitionLink value) {
    return new JAXBElement<DefinitionLink>(_DefinitionLink_QNAME, DefinitionLink.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link CalculationLink }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link CalculationLink }{@code >}
   */
  @XmlElementDecl(namespace = "http://www.xbrl.org/2003/linkbase", name = "calculationLink", substitutionHeadNamespace = "http://www.xbrl.org/2003/XLink", substitutionHeadName = "extended")
  public JAXBElement<CalculationLink> createCalculationLink(CalculationLink value) {
    return new JAXBElement<CalculationLink>(_CalculationLink_QNAME, CalculationLink.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link LabelLink }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link LabelLink }{@code >}
   */
  @XmlElementDecl(namespace = "http://www.xbrl.org/2003/linkbase", name = "labelLink", substitutionHeadNamespace = "http://www.xbrl.org/2003/XLink", substitutionHeadName = "extended")
  public JAXBElement<LabelLink> createLabelLink(LabelLink value) {
    return new JAXBElement<LabelLink>(_LabelLink_QNAME, LabelLink.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceLink }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link ReferenceLink }{@code >}
   */
  @XmlElementDecl(namespace = "http://www.xbrl.org/2003/linkbase", name = "referenceLink", substitutionHeadNamespace = "http://www.xbrl.org/2003/XLink", substitutionHeadName = "extended")
  public JAXBElement<ReferenceLink> createReferenceLink(ReferenceLink value) {
    return new JAXBElement<ReferenceLink>(_ReferenceLink_QNAME, ReferenceLink.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
   */
  @XmlElementDecl(namespace = "http://www.xbrl.org/2003/linkbase", name = "definition")
  public JAXBElement<String> createDefinition(String value) {
    return new JAXBElement<String>(_Definition_QNAME, String.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link QName }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link QName }{@code >}
   */
  @XmlElementDecl(namespace = "http://www.xbrl.org/2003/linkbase", name = "usedOn")
  public JAXBElement<QName> createUsedOn(QName value) {
    return new JAXBElement<QName>(_UsedOn_QNAME, QName.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link TitleType }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link TitleType }{@code >}
   */
  @XmlElementDecl(namespace = "http://www.xbrl.org/2003/XLink", name = "title")
  public JAXBElement<TitleType> createTitle(TitleType value) {
    return new JAXBElement<TitleType>(_Title_QNAME, TitleType.class, null, value);
  }

}
