//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.19 at 01:31:41 PM CEST 
//


package gov.sec.ratings;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://xbrl.sec.gov/ratings/2015-03-31}RAN"/&gt;
 *         &lt;element ref="{http://xbrl.sec.gov/ratings/2015-03-31}FCD"/&gt;
 *         &lt;choice&gt;
 *           &lt;element ref="{http://xbrl.sec.gov/ratings/2015-03-31}OD" maxOccurs="unbounded"/&gt;
 *           &lt;element ref="{http://xbrl.sec.gov/ratings/2015-03-31}ISD" maxOccurs="unbounded"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *       &lt;attGroup ref="{http://www.xbrl.org/2003/instance}tupleAttrs"/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ran",
    "fcd",
    "od",
    "isd"
})
public class ROCRA {

  @XmlElement(name = "RAN", namespace = "http://xbrl.sec.gov/ratings/2015-03-31", required = true)
  protected StringItemType ran;
  @XmlElement(name = "FCD", namespace = "http://xbrl.sec.gov/ratings/2015-03-31", required = true)
  protected DateItemType fcd;
  @XmlElement(name = "OD", namespace = "http://xbrl.sec.gov/ratings/2015-03-31")
  protected List<OD> od;
  @XmlElement(name = "ISD", namespace = "http://xbrl.sec.gov/ratings/2015-03-31")
  protected List<ISD> isd;
  @XmlAttribute(name = "id")
  @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
  @XmlID
  @XmlSchemaType(name = "ID")
  protected String id;
  @XmlAnyAttribute
  private Map<QName, String> otherAttributes = new HashMap<QName, String>();

  /**
   * Gets the value of the ran property.
   *
   * @return possible object is {@link StringItemType }
   */
  public StringItemType getRAN() {
    return ran;
  }

  /**
   * Sets the value of the ran property.
   *
   * @param value allowed object is {@link StringItemType }
   */
  public void setRAN(StringItemType value) {
    this.ran = value;
  }

  /**
   * Gets the value of the fcd property.
   *
   * @return possible object is {@link DateItemType }
   */
  public DateItemType getFCD() {
    return fcd;
  }

  /**
   * Sets the value of the fcd property.
   *
   * @param value allowed object is {@link DateItemType }
   */
  public void setFCD(DateItemType value) {
    this.fcd = value;
  }

  /**
   * Gets the value of the od property.
   *
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside
   * the JAXB object. This is why there is not a <CODE>set</CODE> method for the od property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   * <pre>
   *    getOD().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list {@link OD }
   */
  public List<OD> getOD() {
    if (od == null) {
      od = new ArrayList<OD>();
    }
    return this.od;
  }

  /**
   * Gets the value of the isd property.
   *
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside
   * the JAXB object. This is why there is not a <CODE>set</CODE> method for the isd property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   * <pre>
   *    getISD().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list {@link ISD }
   */
  public List<ISD> getISD() {
    if (isd == null) {
      isd = new ArrayList<ISD>();
    }
    return this.isd;
  }

  /**
   * Gets the value of the id property.
   *
   * @return possible object is {@link String }
   */
  public String getId() {
    return id;
  }

  /**
   * Sets the value of the id property.
   *
   * @param value allowed object is {@link String }
   */
  public void setId(String value) {
    this.id = value;
  }

  /**
   * Gets a map that contains attributes that aren't bound to any typed property on this class.
   *
   * <p>
   * the map is keyed by the name of the attribute and the value is the string value of the attribute.
   * <p>
   * the map returned by this method is live, and you can add new attribute by updating the map directly. Because of this design, there's no setter.
   *
   * @return always non-null
   */
  public Map<QName, String> getOtherAttributes() {
    return otherAttributes;
  }

}
